rundir = "runs"
webdir = "www"
# virtualenv = ".venv"
# compiledir = "~/.cache/sealevelbayes/pytensor"
datadir = "sealeveldata"
version = "v0.3.4"  # for zenodo and some scripts
default_experiment = "v0.3.4/run_v0.3.4"
experiments = [
    "v0.3.4/run_v0.3.4",
    "v0.3.4/run_v0.3.4_gis-greenland-2e_ais-antarctica-2e",
    "v0.3.4/run_v0.3.4__skip-tidegauge-_glacier-mm21+zemp19-proj2100",
    "v0.3.4/run_v0.3.4__skip-satellite-_glacier-mm21+zemp19-proj2100",
    "v0.3.4/run_v0.3.4__skip-gps-_glacier-mm21+zemp19-proj2100",
    "v0.3.4/run_v0.3.4__skip-tidegauge-satellite-gps-_glacier-mm21+zemp19-proj2100",
    "v0.3.4/run_v0.3.4__skip-satellite-gps-_glacier-mm21+zemp19-proj2100",
    "v0.3.4/run_v0.3.4_vlm-res-spatial-scale-1.0km",
    "v0.3.4/run_v0.3.4_vlm-res-spatial-scale-10.0km",
    "v0.3.4/run_v0.3.4_vlm-res-spatial-scale-1000.0km",
    "v0.3.4/run_v0.3.4_satellite-error-0.1",
    "v0.3.4/run_v0.3.4_tg-error-0.1",
    "v0.3.4/run_v0.3.4_tg-error-0.1_satellite-error-0.1",
    "v0.3.4/run_v0.3.4-wind",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-40c44f",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-23da29",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-02b7c6",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-526523",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-6f15b5",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-375ab3",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-439a7d",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-aca802",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-c796b8",
    "v0.3.4/run_v0.3.4_leave-out-gps-sat-tg-9c01b6",
]
