name: Build on cluster and deploy
on:
  push:
      #branches: [master]
    branches: [deploy]
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build website
        uses: appleboy/ssh-action@master
        with:
          host: cluster.pik-potsdam.de
          username: perrette
          key: ${{ secrets.CLUSTER_SECRET_KEY }}
          port: 22
          command_timeout: 180m
          script_stop: true
          script: |
            set -e
            workdir=/p/projects/isipedia/perrette/sealevel/ci/slr-matthias
            remote=git@github.com:ISI-MIP/slr-tidegauges-future.git
            [ -d "$workdir" ] || git clone $remote $workdir
            cd $workdir
            git fetch $remote
            git reset --hard ${{ github.sha }}
            git lfs pull $remote
            bash scripts/build.sh --wait
            sha=$(git rev-parse --short ${{ github.sha }})
            link=~/www/slr-tidegauges/${{ github.ref_name }}
            rm -f $link && ln -s $sha $link
